<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logica\**" />
    <EmbeddedResource Remove="Logica\**" />
    <None Remove="Logica\**" />
    <Page Remove="Logica\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGG.Datos\SGG.Datos.csproj" />
    <ProjectReference Include="..\SGG.Logica\SGG.Logica.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Formularios\Recepcionista\" />
  </ItemGroup>

</Project>
