<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGG.Datos\SGG.Datos.csproj" />
    <ProjectReference Include="..\SGG.Dominio\SGG.Dominio.csproj" />
  </ItemGroup>

</Project>
